version: '3'
services:
  postgres:
    image: postgres:latest
    ports:  
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - my-data-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "mydatabase"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5050:80

  backend:
    ports:  
      - 5000:80
    build:
      context: ./src/backend/
      dockerfile: ./infra/Dockerfile
    depends_on:
      - postgres

volumes:
  my-data-volume:
